### ISSUE TITLE
fplt.get_slice_xticks

### ISSUE THREAD

**Issue by Rocroc-czp** [ZhaJiMan/calipso-vfm-visualization#1]
你好！今天下载您的这个代码画CALIPSO VFM产品图的时候，在 “构造截面图所需的x轴刻度“ 的代码的 fplt.get_slice_xticks 这个方法里报错：AttributeError: 'NoneType' object has no attribute 'axes'。具体的全部报错信息是：Traceback (most recent call last):
  File "D:/PycharmProjects/DustStorm/util/DrawCALIPSO.py", line 133, in <module>
    lon, lat, ntick=5, decimals=1
  File "D:\Anaconda3\envs\duststorm\lib\site-packages\frykit-0.1.6-py3.7.egg\frykit\plot.py", line 416, in get_slice_xticks
    lon_label = lon_formatter(lon_ticks[i])
  File "D:\Anaconda3\envs\duststorm\lib\site-packages\cartopy\mpl\ticker.py", line 48, in __call__
    if not isinstance(self.axis.axes, GeoAxes):
AttributeError: 'NoneType' object has no attribute 'axes'
我不知道是不是cartopy和frykit 的版本问题，想问下您知道这是什么问题吗，或许能问问您用的是什么版本吗？

**Comment by ZhaJiMan** [comment]
我用的是cartopy=0.21.0，请说说你用的cartopy和matplotlib是什么版本？

**Comment by Rocroc-czp** [comment]
感谢回复！我的cartopy 版本是0.17.0，matplotlib版本是3.5.2。安装的时候自动选的最新可安装的安装的。

**Comment by ZhaJiMan** [comment]
似乎 cartopy<0.18.0 时用来给刻度标签加上 °E 的 `LongitudeFormatter` 类不能直接拿来用，必须要添加到 `GeoAxes` 的 `XAxis` 上才行。另外 frykit 要求 cartopy 的版本至少在 0.20.0 以上。建议升级 cartopy，或者把 frykit 里的 `get_slice_xtick` 函数的源码复制出来，将其中用到 `LongitudeFormatter` 和 `LatitudeFormatter` 的部分去掉，改为手动添加 °E 和 °N 符号。

**Comment by Rocroc-czp** [comment]
十分感谢回复！我先尝试一下直接用字符串拼接，不行的话再试试升级版本，因为版本是环境自动选择的已经是匹配环境的最新环境了。
